import{a as d,S as v,i as a}from"./assets/vendor-CxL-4rjn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const q="53431502-05bc1324bd266ac6e07fa7d19";d.defaults.baseURL="https://pixabay.com/api/";const f=15;async function P(r){const t={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:1};return(await d.get("/",{params:t})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function $(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:n,comments:w,downloads:S})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${i}" alt="${e}" />
            </a>
            <div class="info">
            <p><b>Likes</b> ${o}</p>
            <p><b>Views</b> ${n}</p>
            <p><b>Comments</b> ${w}</p>
            <p><b>Downloads</b> ${S}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t),M.refresh()}function g(){p.innerHTML=""}function B(){m.classList.remove("is-hidden")}function R(){m.classList.add("is-hidden")}function H(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const y=document.querySelector(".form"),O=document.querySelector(".load-more");let b="",c=1,u=0;y.addEventListener("submit",x);O.addEventListener("click",N);async function x(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){a.warning({message:"Please, enter your query",position:"topRight"});return}b=t,c=1,u=0,g(),l(),await L({isNewSearch:!0}),y.reset()}async function N(){await L({isNewSearch:!1})}async function L({isNewSearch:r}){B(),l();try{const t=await P(b,c),{hits:i,totalHits:s}=t;if(r){if(!i.length){g(),a.info({message:"Pictures not found. Try another query",position:"topRight"});return}u=s}if(!i.length){l(),a.info({message:"We are sorry, but you have reached the end of search results",position:"topRight"});return}$(i),c>1&&T();const e=Math.ceil(u/f);c<e?H():(l(),a.info({message:"We are sorry, but you have reached the end of search results",position:"topRight"})),c+=1}catch{a.error({message:"An error occured during loading. Please try again later",position:"topRight"})}finally{R()}}function T(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
