import{a as d,S as v,i as a}from"./assets/vendor-CxL-4rjn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="53431502-05bc1324bd266ac6e07fa7d19";d.defaults.baseURL="https://pixabay.com/api/";const f=15;async function P(r,t){const s={key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:f,page:t};return(await d.get("/",{params:s})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function $(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:n,comments:w,downloads:S})=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${s}" alt="${e}" />
            </a>
            <div class="info">
            <p><b>Likes</b> ${o}</p>
            <p><b>Views</b> ${n}</p>
            <p><b>Comments</b> ${w}</p>
            <p><b>Downloads</b> ${S}</p>
            </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t),M.refresh()}function y(){p.innerHTML=""}function B(){m.classList.remove("is-hidden")}function R(){m.classList.add("is-hidden")}function H(){h.classList.remove("is-hidden")}function c(){h.classList.add("is-hidden")}const g=document.querySelector(".form"),O=document.querySelector(".load-more");let b="",l=1,u=0;g.addEventListener("submit",x);O.addEventListener("click",N);async function x(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){a.warning({message:"Please, enter your query",position:"topRight"});return}b=t,l=1,u=0,y(),c(),await L({isNewSearch:!0}),g.reset()}async function N(){await L({isNewSearch:!1}),T()}async function L({isNewSearch:r}){B(),c();try{const t=await P(b,l),{hits:s,totalHits:i}=t;if(r){if(!s.length){y(),a.info({message:"Pictures not found. Try another query",position:"topRight"});return}u=i}if(!s.length){c(),a.info({message:"We are sorry, but you have reached the end of search results",position:"topRight"});return}$(s);const e=Math.ceil(u/f);l<e?H():(c(),a.info({message:"We are sorry, but you have reached the end of search results",position:"topRight"})),l+=1}catch{a.error({message:"An error occured during loading. Please try again later",position:"topRight"})}finally{R()}}function T(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
